name: mZUTiOS
options:
  deploymentTarget:
    iOS: '16.0'
settings:
  base:
    SWIFT_VERSION: '5.10'
targets:
  mZUTCore:
    type: framework
    platform: iOS
    sources:
      - path: Sources/mZUTCore
    settings:
      base:
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: Sources/mZUTCore/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: pl.kejlo.mzut.core
  mZUTiOSApp:
    type: application
    platform: iOS
    sources:
      - path: Sources/mZUTiOSApp
    dependencies:
      - target: mZUTCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: pl.kejlo.mzut.ios
        INFOPLIST_FILE: Sources/mZUTiOSApp/Info.plist
        SUPPORTS_MACCATALYST: NO
  mZUTCoreTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/mZUTCoreTests
    dependencies:
      - target: mZUTCore
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: pl.kejlo.mzut.core.tests
schemes:
  mZUTiOSApp:
    build:
      targets:
        mZUTiOSApp: all
        mZUTCore: all
    test:
      targets:
        - mZUTCoreTests
